### ISSUE TITLE
No multilingual support

### ISSUE THREAD

**Issue by choybe** [ATM-Consulting/dolibarr_module_referenceletters#142]
I just made a test on an English Dolibarr-version (16). The printout of the body of the document templates only works in french., When generating the document with other languages only header and footer are generated. The body stays blank. I conclude, therefore, somewhere here the multilingual support is missing.

**Comment by atm-lena** [comment]
Hello, 
Can you tell us if this issue is still valid ?

**Comment by choybe** [comment]
No furher follow up. Can be closed
