### ISSUE TITLE
IMPRESSION IMPOSSIBLE / IMAGE / 

### ISSUE THREAD

**Issue by clicqueur2** [ATM-Consulting/dolibarr_module_referenceletters#74]
Bonjour 
Je me permets de revenir vers vous car j'ai différents soucis 
Le premier c'est que mes contrats que je générer ne sont pas imprimable ce qui est un peu embêtant vis à vis de mes clients :D
je viens d'essayer avec le dernier master aucun changement
que les images que j'ai dans mon serveur ne sont jamais généré dans aucun de mes documents propal/facture/contrat/...

[CT2005-0007 (17).pdf](https://github.com/ATM-Consulting/dolibarr_module_referenceletters/files/4694087/CT2005-0007.17.pdf)
![Annotation 2020-05-28 095449](https://user-images.githubusercontent.com/64977787/83114517-526d8000-a0c9-11ea-8cb2-cd06db257a60.jpg)
![Annotation 2020-05-28 095458](https://user-images.githubusercontent.com/64977787/83114520-54374380-a0c9-11ea-9acb-42f80fe3270d.jpg)

**Comment by atm-florian** [comment]
Il est possible que votre configuration serveur web soient à adapter pour permettre la récupération de image dans les PDFcréér depuis DocEdit.
Avez vous regardes les log acces.log de votre serveur web au moment de la génération ? Vous devriez y trouver les informations pour configurer correctement votre serveur web.
Pour l'impression du document.... si le PDF s'affiche dans votre lecteur  de PDF (ici Acrobat reader) c'est qu'il est valide, s'il ne s'imprime pas c'est le logiciel lecteur PDF qui bloque, cela n'est pas du à DocEdit

**Comment by clicqueur2** [comment]
Bonjour merci de votre reponse mais si c'était un soucis de serveur est ce que le logo s'imprimerais avec le modèle azur qui ne sort pas de doc edit ?
Cordialement
